//https://www.typescriptlang.org/play?useDefineForClassFields=true&experimentalDecorators=true#code/MYGwhgzhAEDC0G8BQ1oCcCmBHAXNMAdgJ5IrTAD2BEALmgK7A0VoAUAlImajQBYCWEAHSYs0ALxdU0-HgDksOd2gBfMitRI1SUJBgAhaBgAeNDAQAmMeMlSi8hEmUrU6jZm063pEegAcMT1IZPkERbAkpGWghWNDhUQAaZVQAI3l9JRk1VDVtF1poVMiCDAB3aH0OUgKKEAwhEAoAc1ZU8Kx2UiA
export const ParentAndChild = () => {};
